[frontend] feat: add edit button
CS3219-AY2324S1/ay2324s1-course-assessment-g17 pull request #35
Opened 2023-09-12 12:25 UTC by juslam19

2023-09-12 14:16 UTC, seelengxd commented on frontend/src/components/questions/QuestionEditIconButton.tsx
> +          navigate(`/question/edit/${questionId}`);
url changed in #27 

as for the aesthetic changes - i'll leave it to someone else to approve :P

2023-09-12 19:36 UTC, chloeelim commented
Thanks for working on this! This is just a minor nit but I personally think it might be better to remove the colors on the buttons in the question list as it feels a little too overwhelming (too much cognitive overload, attention goes to the button column instead of the 'more important' data)- this might be a personal preference though, so feel free to disagree! :)

|No color|Color|
|----|----|
| <img width="1366" alt="Screenshot 2023-09-13 at 3 25 51 AM" src="https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g17/assets/79991214/03bb0345-9afd-47ea-9814-b78020c7ae98"> |  <img width="1377" alt="Screenshot 2023-09-13 at 3 26 28 AM" src="https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g17/assets/79991214/938b79a2-b8b5-43d0-9461-526b2bbd91f3">    |

2023-09-13 01:17 UTC, sltsheryl commented
> Thanks for working on this! This is just a minor nit but I personally think it might be better to remove the colors on the buttons in the question list as it feels a little too overwhelming (too much cognitive overload, attention goes to the button column instead of the 'more important' data)- this might be a personal preference though, so feel free to disagree! :)
> 
> No color	Color
> <img alt="Screenshot 2023-09-13 at 3 25 51 AM" width="1366" src="https://user-images.githubusercontent.com/79991214/267440760-03bb0345-9afd-47ea-9814-b78020c7ae98.png">	<img alt="Screenshot 2023-09-13 at 3 26 28 AM" width="1377" src="https://user-images.githubusercontent.com/79991214/267440800-938b79a2-b8b5-43d0-9461-526b2bbd91f3.png">

we shd also consider if the delete button (a bin icon) is beside, it’s abit too many things in the table. should we make the edit in the individual question page or it’s okay to have three buttons in each row

2023-09-14 11:17 UTC, juslam19 commented
Changed button colours to gray, except arrow which is blue

2023-09-15 10:54 UTC, seelengxd requested changes, later dismissed

2023-09-15 10:54 UTC, seelengxd commented on frontend/src/components/questions/QuestionViewIconButton copy.tsx
name change causing code to not compile

2023-09-15 10:56 UTC, juslam19 commented on frontend/src/components/questions/QuestionViewIconButton copy.tsx
Can you screenshot the errors? I do not have these issues.

2023-09-15 10:58 UTC, seelengxd commented on frontend/src/components/questions/QuestionViewIconButton copy.tsx
hmm maybe its something wrong on my end let me check my bad

<img width="758" alt="image" src="https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g17/assets/34371483/e4277691-ce81-49a9-8cea-dba07abb58a0">

2023-09-15 11:14 UTC, seelengxd commented on frontend/src/components/questions/QuestionViewIconButton copy.tsx
ok nvm fixed 👍

2023-09-20 13:26 UTC, sltsheryl commented
@chloeelim ^what do you think abt the colors 🤔

2023-09-27 09:31 UTC, sltsheryl approved these changes
- i changed the position of edit button to the individual question instead (we should only show this to admins) 
- restyled the delete and view buttons

# Initial
<img width="500" alt="Screenshot 2023-09-27 at 5 03 27 PM" src="https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g17/assets/96589109/47773e25-28c7-4e83-88bd-d841b0e13ec1">

# Updated
<img width="700" alt="Screenshot 2023-09-27 at 5 26 53 PM" src="https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g17/assets/96589109/1b07dba5-7f9e-465e-a18f-bd5804388bdc">

<img width="446" alt="Screenshot 2023-09-27 at 5 26 58 PM" src="https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g17/assets/96589109/1126bda3-485d-4d44-acc2-74bdd0f6d13a">

2023-09-27 09:32 UTC, merged